### ISSUE TITLE
Example doesnt work

### ISSUE THREAD

**Issue by 89z** [deluan/lookup#5]
If I try to run the example, I get this:

~~~
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xc0610e]

goroutine 1 [running]:
github.com/deluan/lookup.ensureGrayScale(0x0, 0x0, 0x0, 0x0)
        C:/lookup/helpers.go:14 +0x6e
github.com/deluan/lookup.(*OCR).Recognize(0xc00011df48, 0x0, 0x0, 0x0, 0xc000048320, 0xc00005a000, 0xc000043f48)
        C:/lookup/ocr.go:85 +0x45
main.main()
        C:/lookup/test/examples_ocr.go:30 +0xd2
~~~

https://github.com/deluan/lookup/blob/a12095427a5620a9f542a10f49c99eb9d1286597/helpers.go#L14
https://github.com/deluan/lookup/blob/a12095427a5620a9f542a10f49c99eb9d1286597/ocr.go#L85
https://github.com/deluan/lookup/blob/a12095427a5620a9f542a10f49c99eb9d1286597/examples_ocr_test.go#L30

**Comment by 89z** [comment]
Looks like the problem is here:

https://github.com/deluan/lookup/blob/a12095427a5620a9f542a10f49c99eb9d1286597/examples_ocr_test.go#L3-L8

need to add:

~~~go
_ "image/png"
~~~

**Comment by deluan** [comment]
I think it is fair to add the import you suggested, as a "complete" example, but the examples in the repository clearly work as they are part of the documentation and they are run and show the results when generating the docs: https://pkg.go.dev/github.com/deluan/lookup#example-package-Lookup

Most probably because they are part of the `lookup` package, and some other file in the folder is import the `image/png` package. They fail only if ran individually.
